add stdin-filename support
rhysd/actionlint pull request #157
Opened 2022-06-23 12:39 UTC by arahatashun

## What
add support for overwriting file names when using stdin.
## Why
When I tried developing a VSCode extension for actionlint, I felt it would be helpful if we had this option.
FYI: https://github.com/fnando/vscode-linter/blob/main/docs/creating-linters.md

For example, eslint has this kind of option. https://eslint.org/docs/user-guide/command-line-interface#--stdin-filename
## QA
With --stdin-filename 
```
shun@Mac-mini actionlint % echo "foo"|  ./actionlint --stdin-filename "test.yml" -
test.yml:1:1: workflow is scalar node but mapping node is expected [syntax-check]
  |
1 | foo
  | ^~~
test.yml:1:1: "jobs" section is missing in workflow [syntax-check]
  |
1 | foo
  | ^~~
```
Without --stdin-filename 
```
shun@Mac-mini actionlint % echo "foo"|  ./actionlint -
<stdin>:1:1: workflow is scalar node but mapping node is expected [syntax-check]
  |
1 | foo
  | ^~~
<stdin>:1:1: "jobs" section is missing in workflow [syntax-check]
  |
1 | foo
  | ^~~
```

2022-06-24 13:23 UTC, rhysd requested changes

2022-06-24 13:23 UTC, rhysd commented on command.go
> +		}
```suggestion
		n := "<stdin>"
		if opts.StdInFileName != "" {
			n = opts.StdInFileName
		}
		return l.Lint(n, b, nil)
```

Would you reduce repeating code?

2022-06-24 13:23 UTC, rhysd commented on linter.go
> +	StdInFileName string
Could you rename this to `StdinFileName` since stdin is one word?

2022-06-24 13:24 UTC, rhysd commented
@arahatashun When you finish to build the VS Code plugin, I would be glad to hear that. I'll update document to include the URL to the project.

2022-06-24 15:38 UTC, rhysd approved these changes

2022-06-24 15:49 UTC, rhysd commented
Thanks!

2022-06-24 15:49 UTC, merged

2022-06-26 13:53 UTC, rhysd commented
This change was included in the latest release [v1.6.14](https://github.com/rhysd/actionlint/releases/tag/v1.6.14).

2022-06-26 15:30 UTC, arahatashun commented
Thank you for the quick release. I published the VSCode extension <https://marketplace.visualstudio.com/items?itemName=arahata.linter-actionlint>.

2022-07-05 06:38 UTC, itsmeboy0 commented
@rhysd Can you add a reference to it in the docs now?

2022-07-06 11:03 UTC, rhysd commented
I'm sorry for catching the comment lately since this issue was already closed. I added description about the VS Code extension. Thank you for making it!

https://github.com/rhysd/actionlint/commit/49dede4f36dcb71b90d1847094458a5562295e9b