remove `macos-12` runner label
rhysd/actionlint pull request #465
Opened 2024-10-21 09:14 UTC by shogo82148

The macOS 12 runner image has been deprecated on 10/7/2024, and will be fully unsupported by 12/3/2024

- https://github.com/actions/runner-images/issues/10721
- https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/

2024-10-21 09:30 UTC, rhysd commented
Thanks. I believe we should merge this after 2024 12/3 and after this issue has been closed.

https://github.com/actions/runner-images/issues/10721

2024-10-21 09:32 UTC, rhysd requested changes
This review comment is to block the merge until the runner is completely dropped.

2024-12-16 21:22 UTC, AlexSkrypnyk commented
Also, `macos-15` is available, but reported as false positive by actionlint.

2024-12-17 02:42 UTC, rhysd commented
`macos-15` was supported at 1.7.3. If actionlint still complains about it, it should be a bug.

https://github.com/rhysd/actionlint/releases/tag/v1.7.3

2024-12-19 17:42 UTC, closed without merging